### ISSUE TITLE
Fix random failures from Travis CI

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2161]
Our builds always have some random failures every now and then. We can use this issue as an ongoing tracker to record down these failures, and then systematically fix them. 

### Random failures
14 Dec
```
rspec ./spec/features/course/assessment/submission/manually_graded_spec.rb:88 # Course: Assessment: Submissions: Manually Graded Assessments with tenant :instance As a Course Student I can finalise my submission only once

1) Course: Assessment: Submissions: Manually Graded Assessments with tenant :instance As a Course Student I can finalise my submission only once
    Failure/Error: sleep 0.1 until page.all(‘.confirm-btn’).empty?
   
    Timeout::Error:
      execution expired
```

29 Aug
```
Failures:
  1) System: Administration: Users with tenant :instance As a System Administrator I can search users
     Got 2 failures:
     1.1) Failure/Error: expect(page).to have_content_tag_for(random_user)
            expected #<Capybara::Session> to have content tag for #<User id: 0, name: "System", role: 0, time_zone: nil, profile_photo: nil, encrypted_password: "", au...ip: nil, last_sign_in_ip: nil, created_at: "2017-08-29 06:21:08", updated_at: "2017-08-29 06:21:08">
          # ./spec/features/system/admin/user_management_spec.rb:78:in `block (4 levels) in <top (required)>'
     1.2) Failure/Error: expect(all('.user').count).to eq(1)
          
            expected: 1
                 got: 25
          
            (compared using ==)
          # ./spec/features/system/admin/user_management_spec.rb:79:in `block (4 levels) in <top (required)>'
Finished in 3 minutes 29.5 seconds (files took 13.05 seconds to load)
363 examples, 1 failure, 1 pending
Failed examples:
rspec ./spec/features/system/admin/user_management_spec.rb:61 # System: Administration: Users with tenant :instance As a System Administrator I can search users
```

#### Not too sure yet
```
```

#### Should be fixed
```
```

**Comment by allenwq** [comment]
Random failure, have seen it a few times
```
1) Course: Assessments: Submissions: Programming Answers with tenant :instance As a Course Student I can save my submission
     # Removed add/delete file links for CS1010S
     Failure/Error: super
     
     Capybara::ElementNotFound:
       Unable to find field "filename"
     # ./spec/features/course/assessment/answer/programming_answer_spec.rb:33:in `block (7 levels) in <top (required)>'
     # ./spec/features/course/assessment/answer/programming_answer_spec.rb:32:in `block (6 levels) in <top (required)>'
     # ./spec/features/course/assessment/answer/programming_answer_spec.rb:31:in `each_with_index'
     # ./spec/features/course/assessment/answer/programming_answer_spec.rb:31:in `block (5 levels) in <top (required)>'
     # ./spec/features/course/assessment/answer/programming_answer_spec.rb:30:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:106:in `block (2 levels) in <top (required)>'
Failures:
  1) Course: Assessment: Submissions: Autograded with tenant :instance As a Course Student I can add an attachment to a file upload question
     Failure/Error: expect(page).to have_selector('a', text: 'text.txt')
       expected to find css "a" with text "text.txt" but there were no matches. Also found "layout.coursemology", "layout.navbar.courses", "", "", "", "layout.navbar.help", "user 33", "", "", "Course 149001790339", "activerecord.attributes.course/assessment/category/title.default", "Assessment 18", "", "student 10", "layouts.course_user_badge.achievements 0", "layouts.course_user_badge.levels 0", "course.announcements.sidebar_title", "activerecord.attributes.course/assessment/category/title.default", "course.assessment.submissions.sidebar_title", "course.achievement.achievements.sidebar_title", "course.discussion.topics.sidebar_title", "course.leaderboards.sidebar_title", "course.users.sidebar_title", "course.lesson_plan.items.sidebar_title", "course.material.sidebar_title", "course.forum.forums.sidebar_title", "1", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", which matched the selector but not all filters.
     # ./spec/features/course/assessment/submission/autograded_spec.rb:220:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:106:in `block (2 levels) in <top (required)>'
```
