### ISSUE TITLE
Failing specs on CI

### ISSUE THREAD

**Issue by jeremyyap** [Coursemology/coursemology2#3167]
1. `spec/features/course/assessment/question/programming_management_spec.rb:93 # Course: Assessments: Questions: Programming Management with tenant :instance As a Course Manager I can edit a question`

2. `spec/features/course/assessment/question/programming_management_spec.rb:124 # Course: Assessments: Questions: Programming Management with tenant :instance As a Course Manager I can create a new question and upload the template package`

```
  3) Course::ConsolidatedOpeningReminderNotifier with tenant :instance #opening_reminder sends an email notification
     Failure/Error: expect { subject }.to change { ActionMailer::Base.deliveries.count }.by(2)
       expected `ActionMailer::Base.deliveries.count` to have changed by 2, but was changed by 3
     # ./spec/notifiers/consolidated_opening_reminder_notifier_spec.rb:22:in `block (4 levels) in <top (required)>'
     # ./spec/support/bullet.rb:7:in `block in extended'
```

```
  4) Course: Duplication with tenant :instance As a Course Administrator when I am a manager in another course I can duplicate objects from that course
     Got 2 failures:
     1.1) Failure/Error: expect(page).to have_css('.spinner')
            expected to find css ".spinner" but there were no matches
          # ./spec/features/course/duplication_spec.rb:73:in `block (5 levels) in <top (required)>'
          # ./spec/spec_helper.rb:111:in `block (2 levels) in <top (required)>'
     1.2) Failure/Error: expect(course.assessments.where(title: assessment_title).count).to be(1)
            expected #<Integer:3> => 1
                 got #<Integer:1> => 0
            Compared using equal?, which compares object identity
            but expected and actual are not the same object. Use
            `expect(actual).to eq(expected)` if you don't care about
            object identity in this example.
          # ./spec/features/course/duplication_spec.rb:75:in `block (5 levels) in <top (required)>'
          # ./spec/spec_helper.rb:111:in `block (2 levels) in <top (required)>'
```

```
  5) Course::Video with tenant :instance callbacks when updating video url updates to the youtube embed url
     Failure/Error: raise ArgumentError, "Invalid component keys: #{keys - allowed_keys}."
     
     ArgumentError:
       Invalid component keys: [:course_videos_component].
     # ./app/models/concerns/course_component_query_concern.rb:87:in `validate_settable_component_keys!'
     # ./app/models/concerns/course_component_query_concern.rb:47:in `set_component_enabled_boolean'
     # ./spec/factories/courses.rb:28:in `block (4 levels) in <top (required)>'
     # ./spec/models/course/video_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./spec/models/course/video_spec.rb:231:in `block (6 levels) in <top (required)>'
     # ./spec/models/course/video_spec.rb:230:in `each'
     # ./spec/models/course/video_spec.rb:230:in `block (5 levels) in <top (required)>'
```
